apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:4.4.6
        name: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: "/data/db"
          name: task-pv-storage
      restartPolicy: Always
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: mongo-claim1
